language: php
php:
  - 7.0
  - 7.1
install:
  - composer install
script:
  - mkdir -p build/logs
  - phpunit --configuration tests/unit-tests/configuration.xml
  - vendor/bin/behat --config tests/behat/behat.yml -v
after_success:
  - travis_retry php vendor/bin/coveralls -v