BartoszBartniczak\EventSourcing\Shop\Email\Email:
  properties:
    id:
      type: BartoszBartniczak\EventSourcing\Shop\Email\Id
    sent:
      exclude: true
    unsuccessfulAttemptsOfSending:
      exclude: true