BartoszBartniczak\EventSourcing\EventAggregate\EventAggregate:
  properties:
    committedEvents:
      expose: false
      exclude: true
    uncommittedEvents:
      expose: false
      exclude: true