BartoszBartniczak\EventSourcing\Shop\Order\Event\OrderHasBeenCreated:
  properties:
    basketId:
      type: BartoszBartniczak\EventSourcing\Shop\Basket\Id
    positions:
      type: array<string,BartoszBartniczak\EventSourcing\Shop\Order\Position\Position>
